# Generated by Django 5.1.7 on 2025-03-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255)),
                ('tag_line', models.CharField(max_length=255)),
                ('puuid', models.CharField(max_length=255)),
                ('top_champs', models.JSONField(default=list)),
            ],
        ),
    ]
